USE [ZooManagement]
GO

/****** Objekt:  Index [IX_Tier_TierartID]    Skriptdatum: 21.08.2026 12:23:54 ******/
CREATE NONCLUSTERED INDEX [IX_Tier_TierartID] ON [dbo].[Tier]
(
	[TierartID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


