USE [master]
GO

/****** Objekt:  Database [ZooManagement]    Skriptdatum: 26.08.2026 14:38:14 ******/
CREATE DATABASE [ZooManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ZooManagement', FILENAME = N'C:\SQL-Kurs\DB\ZooManagement\ZooManagement.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ZooManagement_log', FILENAME = N'C:\SQL-Kurs\DB\ZooManagement\ZooManagement_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ZooManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ZooManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ZooManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ZooManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ZooManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ZooManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [ZooManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ZooManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ZooManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ZooManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ZooManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ZooManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ZooManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ZooManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ZooManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ZooManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ZooManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ZooManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ZooManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ZooManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ZooManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ZooManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ZooManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ZooManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [ZooManagement] SET  MULTI_USER 
GO

ALTER DATABASE [ZooManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ZooManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ZooManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ZooManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ZooManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ZooManagement] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [ZooManagement] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ZooManagement] SET QUERY_STORE = ON
GO

ALTER DATABASE [ZooManagement] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ZooManagement] SET  READ_WRITE 
GO


